version: '2'

services:
  example-db:
    container_name: example-db
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=examplerootpassword
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=examplepassword
    restart: always

  fs-db-backup:
    container_name: fs-db-backup
    image: unclephil/docker-db-backup-rclone
    links:
     - example-db
    volumes:
      - ./backups:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=example-db
      - DB_NAME=example
      - DB_USER=example
      - DB_PASS="examplepassword"
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - CHECKSUM=SHA1
      - COMPRESSION=ZSTD
      - SPLIT_DB=FALSE
    restart: always

  rclone-db-backup:
    container_name: rclone-db-backup
    image: unclephil/docker-db-backup-rclone
    links:
     - example-db
    volumes:
      - ./backups:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    configs:
      - source: rclone
        target: /opt/rclone/rclone.conf

    environment:
      - DB_TYPE=mariadb
      - DB_HOST=example-db
      - DB_NAME=example
      - DB_USER=example
      - DB_PASS="examplepassword"
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0300
      - DB_CLEANUP_TIME=8640
      - CHECKSUM=SHA1
      - COMPRESSION=ZSTD
      - SPLIT_DB=FALSE
      - RCLONE_REMOTE=minionas
      - RCLONE_PATH=/rclone
      - RCLONE_CONFIG=/opt/rclone/rclone.conf
    restart: always
configs:
  rclone:
    file: ./rclone/rclone.conf

  

